pipeline{
    
    agent any
    
    stages{
        stage('test'){
            steps{
               checkout([$class: 'GitSCM', branches: [[name: '*/master']],
                         doGenerateSubmoduleConfigurations: false, 
                         extensions: [], submoduleCfg: [], 
                         userRemoteConfigs: [[name: 'sample', url: 'https://github.com/sharadrajore/sample.git']]])
            }
        }
    }
}